Implementação de handler POST para a criação de um cliente
PoultryTrader/api pull request #36
Opened 2021-03-18 20:05 UTC by daniellcprg

2021-03-19 15:07 UTC, GCastilho requested changes
Precisa alterar alguns problemas no código

2021-03-19 15:07 UTC, GCastilho commented on src/routes/v1/index.ts
> +router.use('/clients', clients)
Mesa coisa com esse use

2021-03-19 15:07 UTC, GCastilho commented on tests/api/v1/clients.test.ts
> +		expect(response.body).to.have.property('message').that.equals('Success')
Esse that equals tem que checar se retornou a row do cliente do db

Usa um deep.equal com JSON.parse de um JSON.stringify para n dar problema com os Dates

2021-03-19 15:07 UTC, GCastilho commented on tests/api/v1/clients.test.ts
> +		assert.isObject(client)
Dá pra substituir esse reject com um 'rejectOnNotFound' (n sei se esse é o nome da prop) no findUnique

2021-03-19 15:07 UTC, GCastilho commented on tests/api/v1/clients.test.ts
> +			}
Este client tem o mesmo nome que o registerClient que você está tentando criar, então o 403 pode ser um erro de vc criando o mesmo cliente de novo
Acho que trocar o nome desse cliente deve resolver

2021-03-22 17:31 UTC, daniellcprg reviewed
Tudo ok

2021-03-22 19:22 UTC, GCastilho approved these changes

2021-03-22 19:29 UTC, GCastilho approved these changes

2021-03-22 19:32 UTC, merged